package main

import (
	"net/http"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/gin-gonic/gin"

	docs "uacademy/article/docs" // docs is generated by Swag CLI, you have to import it.
)

// @contact.name   API Article
// @contact.url    https://john.doe.com
// @contact.email  john.doe@swagger.io
// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html
func main() {
	// programmatically set swagger info
	docs.SwaggerInfo.Title = "Swagger Example API"
	docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	docs.SwaggerInfo.Version = "1.0"

	InMemoryArticleData = make([]Article, 0)
	r := gin.Default()

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "pong",
		})
	})

	v1 := r.Group("/v2")
	{
		v1.POST("/article", CreateArticle)
		v1.GET("/article/:id", GetArticleByID)
		v1.GET("/article", GetArticleList)
		v1.PUT("/article", UpdateArticle)
		v1.DELETE("/article/:id", DeleteArticle)
	}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":3000") // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}
