info:
  contact:
    email: john.doe@swagger.io
    name: API Article
    url: https://john.doe.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
swagger: "2.0"
